server:
  port: 9090

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/lrabottini/tutorial_microsservicos/tree/master/tutorial_1/delivery_configs